kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    deprecated.daemonset.template.generation: '2'
    openshift.io/generated-by: OpenShiftNewApp
  selfLink: /apis/apps/v1/namespaces/default/daemonsets/bgp-test
  resourceVersion: '288991'
  name: bgp-test
  uid: 2c01134a-79c8-11e9-83bf-025da56a1f26
  creationTimestamp: '2019-05-18T23:53:45Z'
  generation: 2
  namespace: default
  labels:
    app: bgp-test
spec:
  selector:
    matchLabels:
      app: bgp-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgp-test
        deploymentconfig: bgp-test
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      nodeSelector:
        bgp-enabled: 'true'
      restartPolicy: Always
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: exabgp-init-container
          command:
            - sh
            - '-c'
            - >-
              cat /config/templates/exabgp.conf | sed
              "s/_NODE_IP_/$MY_NODE_IP/g" > /config/exabgp/exabgp.conf && sed -i
              "s/_POD_IP_/$MY_POD_IP/g" /config/exabgp/exabgp.conf
          env:
            - name: MY_NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: /config/exabgp
            - name: templates-config-volume
              mountPath: /config/templates
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/default/bgp-test@sha256:3dcef4590f0b4449a6e26271b88ab881973c82d7e934cedb7147fb1f51f46e14
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: bgp-test
          image: >-
            image-registry.openshift-image-registry.svc:5000/default/bgp-test@sha256:e915357c0a7c957d24ba122552e2ad239a8f1e11403feb7ece26b8f46f1302ea
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /config/exabgp
            - name: templates-config-volume
              mountPath: /config/templates
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      volumes:
        - name: templates-config-volume
          configMap:
            name: exabgp-config-map
            defaultMode: 420
        - name: config-volume
          emptyDir: {}
      dnsPolicy: ClusterFirst
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
status:
  currentNumberScheduled: 3
  numberMisscheduled: 0
  desiredNumberScheduled: 3
  numberReady: 3
  observedGeneration: 2
  updatedNumberScheduled: 3
  numberAvailable: 3
